package main

import (
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

func TestLintFileAllowsBlankLineBetweenFunctions(t *testing.T) {
	path := writeGoFile(t, "good.go", `package sample

func first() {
}

func second() {
}
`)

	issues, err := lintFile(token.NewFileSet(), path)
	if err != nil {
		t.Fatalf("lint file: %v", err)
	}
	if len(issues) != 0 {
		t.Fatalf("expected no issues, got %#v", issues)
	}
}

func TestLintFileRequiresBlankLineBetweenFunctions(t *testing.T) {
	path := writeGoFile(t, "bad.go", `package sample

func first() {
}
func second() {
}
`)

	issues, err := lintFile(token.NewFileSet(), path)
	if err != nil {
		t.Fatalf("lint file: %v", err)
	}
	if len(issues) != 1 {
		t.Fatalf("expected one issue, got %#v", issues)
	}
	if issues[0].line != 5 {
		t.Fatalf("expected issue on line 5, got %#v", issues[0])
	}
}

func TestLintFileTreatsFunctionDocsAsDeclarationStart(t *testing.T) {
	path := writeGoFile(t, "docs.go", `package sample

func first() {
}
// second documents second.
func second() {
}
`)

	issues, err := lintFile(token.NewFileSet(), path)
	if err != nil {
		t.Fatalf("lint file: %v", err)
	}
	if len(issues) != 1 {
		t.Fatalf("expected one issue, got %#v", issues)
	}
	if issues[0].line != 5 {
		t.Fatalf("expected issue on doc line 5, got %#v", issues[0])
	}
}

func TestLintFileRequiresBlankLineAroundFunctionDeclaration(t *testing.T) {
	path := writeGoFile(t, "mixed.go", `package sample

func first() {
}
var value = 1
func second() {
}
`)

	issues, err := lintFile(token.NewFileSet(), path)
	if err != nil {
		t.Fatalf("lint file: %v", err)
	}
	if len(issues) != 2 {
		t.Fatalf("expected two issues, got %#v", issues)
	}
	if issues[0].line != 5 || issues[1].line != 6 {
		t.Fatalf("expected issues on lines 5 and 6, got %#v", issues)
	}
}

func TestLintFileAllowsBlankLineAroundFunctionDeclaration(t *testing.T) {
	path := writeGoFile(t, "mixed-good.go", `package sample

func first() {
}

var value = 1

func second() {
}
`)

	issues, err := lintFile(token.NewFileSet(), path)
	if err != nil {
		t.Fatalf("lint file: %v", err)
	}
	if len(issues) != 0 {
		t.Fatalf("expected no issues, got %#v", issues)
	}
}

func TestLintFileSkipsGeneratedGo(t *testing.T) {
	path := writeGoFile(t, "generated.go", `// Code generated by test. DO NOT EDIT.
package sample

func first() {
}
func second() {
}
`)

	issues, err := lintFile(token.NewFileSet(), path)
	if err != nil {
		t.Fatalf("lint file: %v", err)
	}
	if len(issues) != 0 {
		t.Fatalf("expected generated file to be skipped, got %#v", issues)
	}
}

func writeGoFile(t *testing.T, name string, content string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return path
}
